version: "3.8"

services:
  backend:
    build: .
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/etshostore
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
