version: "3.8"

services:
  backend:
    build: .
    ports:
      - "4001:4001"
    volumes:
      - .:/app
    environment:
      - PORT=4001
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
